return {
  require("usr.ui.nui").repo,
  require("usr.ui.noice").repo,
  require("usr.ui.notify").repo,
  require("usr.ui.windows").repo,
  require("usr.ui.lualine").repo,
  require("usr.ui.plenary").repo,
  require("usr.ui.winshift").repo,
  require("usr.ui.dressing").repo,
  require("usr.ui.scrollbar").repo,
  require("usr.ui.colorizer").repo,
  require("usr.ui.ts-rainbow").repo,
  require("usr.ui.webdevicons").repo,
  require("usr.ui.smooth-cursor").repo,
  require("usr.ui.mini-indentscope").repo,
  require("usr.ui.indent-blankline").repo,
}
