return {
  require("usr.accessibility.range-highlight").repo,
  require("usr.accessibility.tmux-navigator").repo,
  require("usr.accessibility.vim-illuminate").repo,
  require("usr.accessibility.todo-comments").repo,
  require("usr.accessibility.treesitter").repo,
  require("usr.accessibility.bufferline").repo,
  require("usr.accessibility.telescope").repo,
  require("usr.accessibility.nvim-tree").repo,
  require("usr.accessibility.neo-tree").repo,
  require("usr.accessibility.dashboard").repo,
  require("usr.accessibility.gitsigns").repo,
  require("usr.accessibility.spectre").repo,
  require("usr.accessibility.harpoon").repo,
  require("usr.accessibility.trouble").repo,
  require("usr.accessibility.tabout").repo,
  require("usr.accessibility.leap").repo,
}
